name: Build Pixl.js Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_VERSION: ${{ github.run_number }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y make zip

    - name: Build firmware
      run: cd fw && make all RELEASE=1 APP_VERSION=${{ env.APP_VERSION }} BOARD=OLED

    - name: Package OTA firmware
      run: cd fw && make ota APP_VERSION=${{ env.APP_VERSION }} BOARD=OLED

    - name: List build directory
      run: ls -alh fw/_build/

    - name: Upload OTA artifact
      uses: actions/upload-artifact@v4
      with:
        name: pixljs_fw_OLED_ota
        path: fw/_build/pixjs_ota_v${{ env.APP_VERSION }}.zip
        if-no-files-found: error

    - name: Upload HEX artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: pixljs_fw_OLED_hex
        path: fw/_build/pixljs.hex
        if-no-files-found: warn
